# Alacritty Configuration

[general]
import = [ "~/.config/alacritty/Nordic.toml", ]

[window]
padding         = { x = 3, y = 3 } # Blank space added around the window in pixels.
dynamic_padding = true # Spread additional padding evenly around the terminal content. 
opacity         = 0.95 # Background opacity as a floating point number from 0.0 to 1.0.
blur            = true # Request compositor to blur content behind transparent windows.
title           = "Alacritty" # Window title.

[font]
normal      = { family = "MesloLGS Nerd Font Mono", style = "Regular" }
bold        = { family = "MesloLGS Nerd Font Mono", style = "Bold" }
italic      = { family = "MesloLGS Nerd Font Mono", style = "Italic" }
bold_italic = { family = "MesloLGS Nerd Font Mono", style = "Bold_Italic" }
size = 14

[selection]
save_to_clipboard = true

[cursor]
style          = { shape = "Beam", blinking = "On" }
blink_interval = 500 # Cursor blinking interval in milliseconds.

[mouse]
hide_when_typing = true
bindings         = [ { mouse = "Right", mods = "Control", action = "Paste" }, ] 


