# Bryan slick greeter 
[Greeter]
# Customizing
background=/usr/share/wallpapers-bryan/wallpapers/nord-alley-way.png
background-color=#434c5e
draw-grid=true
draw-user-backgrounds=false
theme-name=Nordic-dwm
icon-theme-name=Papirus-Dark
cursor-theme-name=macOS-White-cursor
cursor-theme-size=32

# font
font-name=MesloLGS Nerd Font Mono 10
xft-antialias=true
xft-hintstyle=hintslight
xft-rgba=rgb
xft-dpi=96

# Bar/Misc
content-align=center
show-a11y=false
show-quit=true
show-keyboard=false
show-power=true
show-hostname=true
show-clock=true
activate-numlock=false
enable-hidpi=auto
